### ISSUE TITLE
[COSMETIC] Notebook displays invalid state after partial mailouts

### ISSUE THREAD

**Issue by mychaelo** [ESOUIMods/ShissuGuildTools#2]
Shissu Notebook has a feature of excluding users from processing by right-clicking their IDs.

However, after the processing is done, Notebook's window displays X+1 out of X jobs, instead of the usual 'DONE' caption.

**Comment by Sharlikran** [comment]
I am glad you like the software but I am not developing this at this time. I will keep it in mind if I see a way to update this.
