### ISSUE TITLE
[BUG] Shissu Notebook: player notes are not correctly attached

### ISSUE THREAD

**Issue by mychaelo** [ESOUIMods/ShissuGuildTools#3]
Shissu Notebook has a feature of viewing the player note by hovering above their UserID.

However, currently it doesn't update correctly with the list sorting / filtering, which results in displaying the notes for unrelated player accounts.

**Comment by Sharlikran** [comment]
Didn't know you had more then one issue. Sorry same answer. I will keep it in mind and if I find a way I'll make an adjustment.
